site_name: IBM HElayers
site_url: https://ibm.github.io/helayers/
site_author: IBM FHE team
site_description: >-
  IBM HElayers homomorphic encryption SDK

# Repository
#repo_name: IBM/helayers
#repo_url: https://github.com/IBM/helayers

nav:
  - Home: index.md
  - Installation: installation.md
  - FHE Overview: 
    - FHE: fhe_overview.md
    - Security models: security.md
    - Designing a solution: solution.md
    - Key Management: keys.md
  - HElayers Overview: 
    - HElayers: overview.md
    - Onnx support: onnx.md
  - Demos: demos.md
  - Release notes: CHANGELOG.md
  - Resources: resources.md
  - API Documentation:
    - Python SDK: python-sdk/latest
    - C++ SDK: cpp-sdk/latest
  - Contact us: contact.md

# Copyright
#copyright: Copyright &copy; 2022 IBM

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.expand=false
  highlightjs: true
  palette:
    primary: blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
